spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "PERF - Wakalaka"
  default-value: "Mundo"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'