spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "PERF - Hello kawaii"
  default-value: "World"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'